### ISSUE TITLE
Decimal Places

### ISSUE THREAD

**Issue by navossoc** [PaesslerAG/go-prtg-sensor-api#2]
Hi, I would like to know how to set decimal places as in the picture below:

![image](https://user-images.githubusercontent.com/2457338/65930060-cfc9df00-e3da-11e9-89f7-9006046906b1.png)

I already tried:
```go
		stats.AddChannel(prtg.SensorChannel{
			DecimalMode: "Custom",
		})
```

and

```go
		stats.AddChannel(prtg.SensorChannel{
			DecimalMode: "2",
		})
```

None seems to work.

I also added two new fields `DecimalDigits` and `DecimalPlaces` (that I saw somewhere on the web) and tried to set them to `"2"` and it doesn't work either.

Any tips?

Thanks.

**Comment by femot** [comment]
Hi @navossoc,

sadly the custom sensor API only supports setting `DecimalMode` to `Auto` or `All`. See the official manual: https://www.paessler.com/manuals/prtg/custom_sensors
The current workaround is to do the rounding directly in the sensor, as descibed here with a Powershell example: https://kb.paessler.com/en/topic/62274-custom-decimal-places-using-powershell-scripts

Cheers,
Alex
